variables:
  DOCKER_DRIVE: overlay2

image: node:8-alpine

services:
  - docker:dind

stages:
  - dependencies
  - stylecheck
  - test
  - build
  - publish

cache:
  key: "$CI_BUILD_REF_SLUG"
  paths:
    - node_modules/

install_dependencies:
  stage: dependencies
  before_script:
    - node -v
    - npm -v
  script:
    - npm install
  after_script:
    - tsc -v

do_lint_check:
  stage: stylecheck
  before_script:
    - npm install
  script:
    - npm run lint

do_format_check:
  stage: stylecheck
  before_script:
    - npm install
  script:
    - npm run prettier:check

run_tests:
  stage: test
  before_script:
    - npm install
  script:
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build_source:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build/

publish_npm:
  stage: publish
  only:
    - tags
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish